openapi: 3.0.0
info:
  title: Sample Mock API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get users
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                - id: faker:uuid
                  name: faker:name
                  email: faker:email
                - id: faker:uuid
                  name: faker:name
                  email: faker:email
    post:
      summary: Add a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Created
